---
language: bash
dist: focal
sudo: enabled
branches:
  only:
    - master
    - development
    - testing

matrix:
  include:
    - name: "CentOS 7"
      env:
        - DISTRO='centos:7'
        - REGISTRY=quay.io/centos
    - name: "CentOS 8"
      env:
        - DISTRO='centos:8'
        - REGISTRY=quay.io/centos
    - name: "CentOS stream 8"
      env:
        - DISTRO='centos:stream8'
        - REGISTRY=quay.io/centos
    - name: "Ubuntu 18.04 (bionic)"
      env:
        - DISTRO='ubuntu:18.04'
        - REGISTRY=mirror.gcr.io/library
    - name: "Ubuntu 20.04 (focal)"
      env:
        - DISTRO='ubuntu:20.04'
        - REGISTRY=mirror.gcr.io/library
    - name: "Debian 9 (stretch)"
      env:
        - DISTRO='debian:stretch'
        - REGISTRY=mirror.gcr.io/library
    - name: "Debian 10 (buster)"
      env:
        - DISTRO='debian:buster'
        - REGISTRY=mirror.gcr.io/library
    - name: "Fedora (latest)"
      env:
        - DISTRO='fedora:latest'
        - REGISTRY=registry.fedoraproject.org
    - name: "Fedora (rawhide)"
      env:
        - DISTRO='fedora:rawhide'
        - REGISTRY=registry.fedoraproject.org

before_install:
  - docker pull ${REGISTRY}/${DISTRO}

install:
  - |
    docker run \
      --detach \
      --rm \
      --tty \
      --privileged \
      --network=host \
      --name recap_on_${DISTRO/:/_} \
      --mount type=bind,src="$(pwd)",dst=/recap \
      ${REGISTRY}/${DISTRO}
  - docker exec recap_on_${DISTRO/:/_} /recap/tests/install_deps.sh ${DISTRO}
  - docker exec recap_on_${DISTRO/:/_} /recap/tests/test_install_recap.sh

script:
  - docker exec recap_on_${DISTRO/:/_} bash -c 'recap --version'
  - docker exec recap_on_${DISTRO/:/_} bash -c 'recaplog --version'
  - docker exec recap_on_${DISTRO/:/_} /recap/tests/run_recap.sh
  - docker exec recap_on_${DISTRO/:/_} bash -c 'ls -tr /var/log/recap/*log | xargs tail -v -n+0'
  - docker exec recap_on_${DISTRO/:/_} /recap/tests/run_recaplog.sh
  - docker exec recap_on_${DISTRO/:/_} bash -c 'tail -v -n+0 /var/log/recap/recaplog.log'
  - docker exec recap_on_${DISTRO/:/_} bash -c 'recap -p list'
  - docker exec recap_on_${DISTRO/:/_} bash -c 'recap -p list enabled'
  - docker exec recap_on_${DISTRO/:/_} bash -c 'recap -p enable all'
  - docker exec recap_on_${DISTRO/:/_} bash -c 'recap -p list enabled'
  - docker exec recap_on_${DISTRO/:/_} bash -c 'recap -p list disabled'
  - docker exec recap_on_${DISTRO/:/_} bash -c 'recap -p disable all'
  - docker exec recap_on_${DISTRO/:/_} bash -c 'recap -p list disabled'
  - docker exec recap_on_${DISTRO/:/_} bash -c 'recap -p list enabled'
